// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PncNext.Infrastructure.Persistence;

#nullable disable

namespace PncNext.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528080317_AddControllerType")]
    partial class AddControllerType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("PncNext.Domain.Entities.CommItemConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaudRate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComPort")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("MotionControllerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtocolProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotionControllerConfigId");

                    b.ToTable("CommItemConfigs");
                });

            modelBuilder.Entity("PncNext.Domain.Entities.MachineOptionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AxisCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAirBlow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasAutoloader")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDustCollector")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPurgeAir")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWaterPump")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IOMapType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MotionControllerConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpindleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ToolPocketType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MotionControllerConfigId");

                    b.ToTable("MachineOptionConfigs");
                });

            modelBuilder.Entity("PncNext.Domain.Entities.MotionControllerConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MotionControllerConfigs");
                });

            modelBuilder.Entity("PncNext.Domain.Entities.CommItemConfig", b =>
                {
                    b.HasOne("PncNext.Domain.Entities.MotionControllerConfig", "MotionControllerConfig")
                        .WithMany("CommItems")
                        .HasForeignKey("MotionControllerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotionControllerConfig");
                });

            modelBuilder.Entity("PncNext.Domain.Entities.MachineOptionConfig", b =>
                {
                    b.HasOne("PncNext.Domain.Entities.MotionControllerConfig", "MotionControllerConfig")
                        .WithMany()
                        .HasForeignKey("MotionControllerConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotionControllerConfig");
                });

            modelBuilder.Entity("PncNext.Domain.Entities.MotionControllerConfig", b =>
                {
                    b.Navigation("CommItems");
                });
#pragma warning restore 612, 618
        }
    }
}
